name: ESLint Fix

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint_fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint Fix
        uses: getsentry/action-eslint-fix@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
